### ISSUE TITLE
Breaking change in latest minor release

### ISSUE THREAD

**Issue by trevor-scheer** [southpolesteve/node-abort-controller#39]
Hey @Ethan-Arrowood, #38 is a breaking change. I'd also argue that just because this lib isn't _needed_ doesn't mean it shouldn't continue to work.

I'm a library author for Apollo Server who supports Node versions 14, 16, 18 (+) and this is part of our runtime code until we drop support for v14. This means that some of our v14 users and all of our 16, 18, + can end up in a broken state.

Can this change be reverted in a patch release please? If not, I'll be pinning to `3.0.x` until we drop node v14, but this will continue to effect users of existing apollo server versions if their lockfiles are updated.

**Comment by glasser** [comment]
I generally agree with Trevor here.

Moreover, even if you do want to issue a release with a maximum `engines` constraint (which I think should be a major version change, and doesn't feel necessary), I would think that you'd want the constraint to be `<15.4.0` rather than the lower one, as people publishing software for even the latest version of (still in LTS) v14 can't assume that their users are using the experimental flag. "Versions where an API is only available via a top-level experimental flag" is a perfectly reasonable place to use a polyfill.

**Comment by edouardr** [comment]
Agreed with what was said before. For those facing this issue, if you have `npm@8` you can use [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json?v=true#overrides) in your `package.json` and target the previous version.

```json
  "overrides": {
    "node-abort-controller": "3.0.1"
  }
```

`pnpm` also supports [`overrides`](https://pnpm.io/package_json#pnpmoverrides). For yarn it's `resolutions`

**Comment by BrandonBlanchard** [comment]
It's worth noting that the above override fix will not work if you're using `hashicorp/terraform-cdk-action` as `node-abort-controller` is installed from the command line rather than using `npm` or `yarn`. 

From the Terraform Deploy github action output:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'node-abort-controller@3.1.0',
npm WARN EBADENGINE   required: { node: '<14.7.0' },
npm WARN EBADENGINE   current: { node: 'v16.19.0', npm: '8.19.3' }
npm WARN EBADENGINE }
```

**Comment by ndelangen** [comment]
This is affecting a lot of storybook users, see:
https://github.com/storybookjs/storybook/issues/20793

**Comment by southpolesteve** [comment]
Apologies all. We didn’t anticipate this would be breaking. We’ll get it
sorted out today.

**Comment by ndelangen** [comment]
Thank you so much for the quick reply / assist @southpolesteve ⭐ 
We appreciate your work!

**Comment by Ethan-Arrowood** [comment]
My apologies folks. I didn't think that field would cause a breaking change. Going to revert and release a patch asap. Again, sorry for the headache!

**Comment by Ethan-Arrowood** [comment]
v3.1.1 has been published removing the `engines` property. Please let me know if this fixes everything!

**Comment by avandorp** [comment]
eclipse-scout/cli on 23.1 branch builds again, other internal builds are recovering. Thanks for the fast fix!

**Comment by yannbf** [comment]
We've tested on our end and Webpack based Storybooks are good now. Thank you so much @Ethan-Arrowood!

**Comment by trevor-scheer** [comment]
Thanks for the quick turnaround @Ethan-Arrowood (and for the PR @yannbf)!
