### ISSUE TITLE
AbortSignal doesn't implement EventTarget

### ISSUE THREAD

**Issue by bisubus** [southpolesteve/node-abort-controller#9]
AbortSignal doesn't fully implement [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget), there's no dispatchEvent method, adding a listener with [onabort](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/onabort) is not supported. A listener receives undefined instead of event object, it could be `{type: 'abort'}` at least.

Also it's expected that a signal has `signal.onabort === null` by default (actually I've been using this to detect non-compliant implementations).

**Comment by southpolesteve** [comment]
Thanks for the report! I'll try and look at adding this sometime next week. If you are feeling adventurous, PRs welcome!

**Comment by bisubus** [comment]
Sure. Hope this helps. Also noticed that `abort` allowed a signal to be triggered multiple times which makes an important difference.

**Comment by southpolesteve** [comment]
Released in 1.1.0
